[package]
name = "clock"
version = "0.1.0"
authors = ["Héctor Ramón Jiménez <hector0193@gmail.com>", "Andrew Mackenzie <andrew@mackenzie-serres.net>"]
edition = "2021"

[dependencies]
iced = { version = "0.12.1", default-features = false, features = ["canvas", "tokio", "debug"] }
chrono = "0.4.24"